// Generated by LiveScript 1.2.0
(function(){
  var co, redis, fn1, fn2, fn3, main, main2, main3;
  co = require('co');
  redis = require('redis');
  fn1 = function(done){
    return setTimeout(function(){
      return done(null, 'hello');
    }, 100);
  };
  fn2 = function(done){
    return setTimeout(function(){
      return done(null, 'word');
    }, 50);
  };
  fn3 = function(count){
    return function(done){
      return setTimeout(function(){
        return done(null, count);
      }, 10);
    };
  };
  main = function*(){
    var client, res;
    client = redis.createClient();
    res = yield function(done){
      return client.get(key, done);
    };
    console.log(res);
  };
  main2 = function(key){
    return function*(){
      var client, i$, ref$, len$, i, res;
      client = redis.createClient();
      for (i$ = 0, len$ = (ref$ = [1, 2, 3, 4, 5]).length; i$ < len$; ++i$) {
        i = ref$[i$];
        res = yield fn$;
        console.log(res);
      }
      function fn$(done){
        return client.get(key + "" + i, done);
      }
    };
  };
  main3 = function*(){
    var i$, ref$, len$, i;
    for (i$ = 0, len$ = (ref$ = [1, 2, 3]).length; i$ < len$; ++i$) {
      i = ref$[i$];
      console.log('--------');
      yield main2('key');
    }
  };
  co(main3)();
}).call(this);
