// Generated by LiveScript 1.2.0
(function(){
  var fn, addTen, slice$ = [].slice;
  fn = function(x, y){
    return x + y;
  };
  addTen = partialize$.apply(this, [fn, [10, void 8], [1]]);
  function partialize$(f, args, where){
    var context = this;
    return function(){
      var params = slice$.call(arguments), i,
          len = params.length, wlen = where.length,
          ta = args ? args.concat() : [], tw = where ? where.concat() : [];
      for(i = 0; i < len; ++i) { ta[tw[0]] = params[i]; tw.shift(); }
      return len < wlen && len ?
        partialize$.apply(context, [f, ta, tw]) : f.apply(context, ta);
    };
  }
}).call(this);
