// Generated by CoffeeScript 1.7.1
(function() {
  var api, express;

  express = require("express");

  api = require("./api_route");

  module.exports = function(app) {
    return app.use("/api", api);
  };

}).call(this);

//# sourceMappingURL=index.map
