// Generated by CoffeeScript 1.7.1
(function() {
  var path;

  path = require("path");

  module.exports = {
    WECHAT_TOKEN: "heron_wechat",
    MONGODB_CONFIG_PATH: path.join(__dirname, "../config/mongo.config")
  };

}).call(this);

//# sourceMappingURL=consts.map
