// Generated by LiveScript 1.2.0
(function(){
  var log4js, logger;
  log4js = require('log4js');
  logger = (function(){
    logger.displayName = 'logger';
    var prototype = logger.prototype, constructor = logger;
    logger.getLogger = function(category){
      return log4js.getLogger(category);
    };
    function logger(){}
    return logger;
  }());
  module.exports = logger;
}).call(this);
