// Generated by CoffeeScript 1.7.1
(function() {
  this.login = (function() {
    function login() {}

    login.get = function(req, res, next) {
      return res.render("account/login", {
        message: req.flash("error")
      });
    };

    return login;

  })();

  this.register = (function() {
    function register() {}

    register.get = function(req, res, next) {
      return res.send("ok");
    };

    return register;

  })();

  module.exports = this;

}).call(this);

//# sourceMappingURL=account_controller.map
