// Generated by LiveScript 1.2.0
(function(){
  var index;
  this.index = index = (function(){
    index.displayName = 'index';
    var prototype = index.prototype, constructor = index;
    index.get = function*(){
      this.body = "get in home;";
    };
    function index(){}
    return index;
  }());
}).call(this);
