// Generated by CoffeeScript 1.7.1
(function() {
  var consts;

  consts = require("../consts/consts");

  this.index = (function() {
    function index() {}

    index.get = function(req, res, next) {
      return res.render("home/index", {
        title: "首页"
      });
    };

    return index;

  })();

  module.exports = this;

}).call(this);

//# sourceMappingURL=home_controller.map
