// Generated by CoffeeScript 1.7.1
(function() {
  this.index = (function() {
    function index() {}

    index.get = function(req, res, next) {
      return res.send("ok");
    };

    index.post = function(req, res, next) {
      return res.send("");
    };

    index.put = function(req, res, next) {
      return res.send("");
    };

    index["delete"] = function(req, res, next) {
      return res.send("");
    };

    return index;

  })();

  module.exports = this;

}).call(this);

//# sourceMappingURL=user_controller.map
