// Generated by LiveScript 1.2.0
(function(){
  var path, fs, koa, log4js, koaStatic, mount, koaRouter, mvc, views, app, logger, log4jsMiddleware, pageNotFound, error;
  path = require('path');
  fs = require('fs');
  koa = require('koa');
  log4js = require('log4js');
  koaStatic = require('koa-static');
  mount = require('koa-mount');
  koaRouter = require('koa-router');
  mvc = require('heron-mvc');
  views = require('./helpers/views');
  app = koa();
  log4js.configure('configure/log4js.json', {});
  logger = log4js.getLogger('normal');
  log4jsMiddleware = function*(next){
    log4js.connectLogger(logger, {
      level: 'debug',
      format: ':method :url'
    });
    logger.debug(this.request.method + " " + this.request.url);
    yield next;
  };
  app.use(log4jsMiddleware);
  app.use(koaStatic(path.join(__dirname, '../public')));
  pageNotFound = function*(next){
    yield next;
    if (this.status !== 404) {
      return;
    }
    this.status = 404;
    switch (this.accepts('html', 'json')) {
    case 'html':
      this.type = 'html';
      this.body = yield views.hogan.render('error/404');
      break;
    case 'json':
      this.body = {
        message: 'Page Not Found'
      };
      break;
    default:
      this.type = 'text';
      this.body = 'Page Not Found';
    }
  };
  app.use(pageNotFound);
  if ('development' === app.env) {
    error = function*(next){
      var e;
      try {
        yield next;
      } catch (e$) {
        e = e$;
        e.status == null && (e.status = 500);
        this.status = e.status;
        this.type = 'html';
        this.body = yield views.hogan.render('error/500', {
          message: error.message,
          error: e
        });
        this.app.emit('error', e, this);
      }
    };
    app.use(error);
  }
  if ('production' === app.env) {
    error = function*(next){
      var e;
      try {
        yield next;
      } catch (e$) {
        e = e$;
        this.status = e.status || 500;
        this.type = 'html';
        this.body = yield views.hogan.render('error/500', {
          message: error.message
        });
        this.app.emit('error', e, this);
      }
    };
    app.use(error);
  }
  app.on('error', function(err){
    console.log(err);
    return;
  });
  views.hogan.layout = 'partials/_layout';
  mvc.route.load({
    routeDir: path.join(__dirname, './routes'),
    controllerDir: path.join(__dirname, './controllers')
  }, function(data){}, function(data){
    var router;
    router = new koaRouter();
    router[data.method]("/" + data.controller + "/" + data.action, data.func);
    if (data.controller === 'home' && data.action === 'index') {
      router[data.method]("/", data.func);
    }
    return app.use(router.middleware());
  });
  app.use(mount('/demo', function*(){
    var h, a, html;
    h = yield render('home/index', {});
    a = render('partials/_layout', {
      title: 'home',
      partials: {
        footer: 'footer'
      }
    });
    html = [yield a];
    html = html.join('\n');
    this.body = html;
  }));
  app.use(mount('/test', function*(){
    this.body = yield views.hogan.render('home/index', {
      partials: {
        footer: '../partials/footer'
      }
    });
  }));
  module.exports = app;
}).call(this);
