// Generated by LiveScript 1.2.0
(function(){
  var consts, helperWechat, logger, wechat;
  consts = require('../consts');
  helperWechat = require('../helpers/wechat')(consts.WECHAT_TOKEN);
  logger = require('../helpers/logger').getLogger('controller');
  this.wechat = wechat = (function(){
    wechat.displayName = 'wechat';
    var prototype = wechat.prototype, constructor = wechat;
    wechat.get = function*(){
      if (!helperWechat.checkSignature(this.request.query)) {
        this.status = 200;
        this.body = '';
      } else {
        this.status = 200;
        this.body = this.request.query.echostr;
      }
    };
    wechat.post = function*(){
      logger.info('------------------ post api/wechat ----------------------');
      this.body = 'post';
    };
    function wechat(){}
    return wechat;
  }());
}).call(this);
