// Generated by LiveScript 1.2.0
(function(){
  var co, consts, redisClient, flash, index, test;
  co = require('co');
  consts = require('../consts');
  redisClient = require('../helpers/redis');
  flash = require('../helpers/flash');
  this.index = index = (function(){
    index.displayName = 'index';
    var prototype = index.prototype, constructor = index;
    index.get = function*(){
      this.body = 'ok';
    };
    function index(){}
    return index;
  }());
  this.test = test = (function(){
    test.displayName = 'test';
    var prototype = test.prototype, constructor = test;
    test.get = function*(){
      this.body = yield function(done){
        return co(flash.yieldIsExists(this.request.query.id, 3))(function(err, res){
          return done(err, res);
        });
      };
    };
    function test(){}
    return test;
  }());
}).call(this);
