// Generated by CoffeeScript 1.7.1
(function() {
  var express, logger, path;

  express = require("express");

  logger = require("morgan");

  path = require("path");

  module.exports = function(app) {
    app.use(logger("dev"));
    app.use(express["static"](path.join(__dirname, "public")));
    if ("development" === app.get("env")) {
      0;
    }
    if ("production" === app.get("env")) {
      return 0;
    }
  };

}).call(this);

//# sourceMappingURL=express.map
