// Generated by CoffeeScript 1.7.1
(function() {
  var dateFileLog, log4js;

  log4js = require("log4js");

  log4js.configure("config/log4js.config", {});

  dateFileLog = log4js.getLogger("default");

  module.exports = function(app) {
    return app.use(log4js.connectLogger(dateFileLog, {
      level: "debug",
      format: ":method :url"
    }));
  };

}).call(this);

//# sourceMappingURL=log4js.map
