// Generated by LiveScript 1.2.0
(function(){
  var consts, repository_base, class_schema, class_repository;
  consts = require('../consts');
  repository_base = require('./repository_base');
  class_schema = require('../schemas/class_schema');
  class_repository = (function(superclass){
    var prototype = extend$((import$(class_repository, superclass).displayName = 'class_repository', class_repository), superclass).prototype, constructor = class_repository;
    function class_repository(){
      class_repository.superclass.call(this, consts.CONFIGURE.env.mongo);
      this.model = this.connection.model('class', class_schema);
    }
    return class_repository;
  }(repository_base));
  module.exports = class_repository;
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
