// Generated by LiveScript 1.2.0
(function(){
  var consts, repository_base, curriculum_schema, curriculum_repository;
  consts = require('../consts');
  repository_base = require('./repository_base');
  curriculum_schema = require('../schemas/curriculum_schema');
  curriculum_repository = (function(superclass){
    var prototype = extend$((import$(curriculum_repository, superclass).displayName = 'curriculum_repository', curriculum_repository), superclass).prototype, constructor = curriculum_repository;
    function curriculum_repository(){
      curriculum_repository.superclass.call(this, consts.CONFIGURE.env.mongo);
      this.model = this.connection.model('curriculum', curriculum_schema);
    }
    return curriculum_repository;
  }(repository_base));
  module.exports = curriculum_repository;
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
