// Generated by CoffeeScript 1.7.1
(function() {
  var logger;

  logger = require("../helper/logger").getLogger("test_controller");

  this.action1 = (function() {
    function action1() {}

    action1.get = function(req, res, next) {
      return res.send("get in test");
    };

    action1.post = function(req, res, next) {
      return res.send("post in test");
    };

    return action1;

  })();

  this.action = (function() {
    function action() {}

    action.get = function(req, res, next) {
      return res.send("get");
    };

    return action;

  })();

  module.exports = this;

}).call(this);

//# sourceMappingURL=test_controller.map
