// Generated by LiveScript 1.2.0
(function(){
  var mongoose, classSchema;
  mongoose = require('mongoose');
  classSchema = new mongoose.Schema({
    'class': {
      type: String
    }
  });
  module.exports = curriculumSchema;
}).call(this);
