// Generated by LiveScript 1.2.0
(function(){
  var path, fs, koa, log4js, koaStatic, mount, koaRouter, mvc, app, logger, log4jsMiddleware, pageNotFound, error, router;
  path = require('path');
  fs = require('fs');
  koa = require('koa');
  log4js = require('log4js');
  koaStatic = require('koa-static');
  mount = require('koa-mount');
  koaRouter = require('koa-router');
  mvc = require('heron-mvc');
  app = koa();
  log4js.configure('configure/log4js.json', {});
  logger = log4js.getLogger('normal');
  log4jsMiddleware = function*(next){
    log4js.connectLogger(logger, {
      level: 'debug',
      format: ':method :url'
    });
    logger.debug(this.request.method + " " + this.request.url);
    yield next;
  };
  app.use(log4jsMiddleware);
  app.use(koaStatic(path.join(__dirname, '../public')));
  pageNotFound = function*(next){
    yield next;
    if (this.status !== 404) {
      return;
    }
    this.status = 404;
    switch (this.accepts('html', 'json')) {
    case 'html':
      this.type = 'html';
      this.body = 'Page Not Found';
      break;
    case 'json':
      this.body = {
        message: 'Page Not Found'
      };
      break;
    default:
      this.type = 'text';
      this.body = 'Page Not Found';
    }
  };
  app.use(pageNotFound);
  if ('development' === app.env) {
    error = function*(next){
      var e;
      try {
        yield next;
      } catch (e$) {
        e = e$;
        this.status = e.status || 500;
        this.type = 'html';
        this.body = 'error 500';
        this.app.emit('error', e, this);
      }
    };
    app.use(error);
  }
  if ('production' === app.env) {
    error = function*(next){
      var e;
      try {
        yield next;
      } catch (e$) {
        e = e$;
        this.status = e.status || 500;
        this.type = 'html';
        this.body = 'error 500';
        this.app.emit('error', e, this);
      }
    };
    app.use(error);
  }
  app.on('error', function(err){
    logger.error(err);
    return;
  });
  router = new koaRouter();
  mvc.route.load({
    routeDir: path.join(__dirname, './routes'),
    controllerDir: path.join(__dirname, './controllers')
  }, function(data){}, function(data){
    router[data.method]("/" + data.controller + "/" + data.action, data.func);
    if (data.controller === 'home' && data.action === 'index') {
      return router[data.method]("/", data.func);
    }
  });
  app.use(router.middleware());
  module.exports = app;
}).call(this);
