// Generated by CoffeeScript 1.8.0
(function() {
  var app, dateFileLog, express, log4js, path, routes;

  path = require("path");

  express = require("express");

  log4js = require("log4js");

  routes = require("./lib/routes");

  app = express();

  app.enable("case sensitive routing");

  log4js.configure("config/log4js.config", {});

  dateFileLog = log4js.getLogger("normal");

  app.use(log4js.connectLogger(dateFileLog, {
    level: "debug",
    format: ":method :url"
  }));

  app.use(express["static"](path.join(__dirname, "/public")));

  if ("development" === app.get("env")) {
    console.log("run as development..");
  }

  if ("production" === app.get("env")) {
    console.log("run as production..");
  }

  routes(app);

  app.use(function(req, res, next) {
    var err;
    err = new Error("Not Found");
    err.status = 404;
    return next(err);
  });

  if ("development" === app.get("env")) {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.send({
        message: err.message,
        error: err.stack
      });
    });
  }

  if ("production" === app.get("env")) {
    0;
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.send({
      message: err.message
    });
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=app.js.map
