// Generated by CoffeeScript 1.7.1
(function() {
  var controller, express, router;

  express = require("express");

  router = express.Router();

  controller = function() {};

  controller.wechat = {
    get: function(req, res, next) {
      return res.send("this is get!!!!!!!!!!!");
    },
    post: function(req, res, next) {
      logger.info(req.body);
      return res.send("this is post");
    }
  };

  module.exports = controller;

}).call(this);

//# sourceMappingURL=api_controller.map
