// Generated by CoffeeScript 1.7.1
(function() {
  var consts, controller, encrypt, express, router;

  consts = require("../consts/consts");

  encrypt = require("../helper/encrypt");

  express = require("express");

  router = express.Router();

  controller = function() {};

  controller.wechat = {
    get: function(req, res, next) {
      var nonce, signature, str, strHash, timestamp, token;
      token = consts.WECHAT_TOKEN;
      signature = req.query.signature;
      timestamp = req.query.timestamp;
      nonce = req.query.nonce;
      str = [token, timestamp, nonce].sort().join("");
      strHash = encrypt.sha1Hash(str);
      if (strHash === signature) {
        return res.send(200, req.query.echostr);
      } else {
        return res.send(200, false);
      }
    },
    post: function(req, res, next) {
      return res.send("this is post");
    }
  };

  module.exports = controller;

}).call(this);

//# sourceMappingURL=api_controller.map
