// Generated by CoffeeScript 1.7.1
(function() {
  var assert, consts, repository_base, user_schema;

  repository_base = require("./require")("repository/repository_base");

  user_schema = require("./require")("schema/user_schema");

  consts = require("./require")("consts/consts");

  assert = require("assert");

  describe("repository_base", function() {
    return describe("#ctor", function() {
      return it("should return -1 when value is not found", function() {
        assert.equal(-1, [1, 2, 3].indexOf(5));
        return assert.equal(-1, [1, 2, 3].indexOf(10));
      });
    });
  });

}).call(this);

//# sourceMappingURL=repository.test.map
