// Generated by CoffeeScript 1.7.1
(function() {
  var consts, mongoose, repository_base, test_helper, user_schema;

  test_helper = require("./test_helper");

  mongoose = require("mongoose");

  repository_base = test_helper.require("repository/repository_base");

  user_schema = test_helper.require("schema/user_schema");

  consts = test_helper.require("consts/consts");

  describe("repository_base", function() {
    return describe("#ctor", function() {
      return it("should return -1 when value is not found", function() {
        var rep;
        rep = new repository_base(consts.MONGODB_CONFIG_PATH);
        rep.model = rep.connection.model("user", user_schema);
        return rep.save({
          username: "test",
          password: "test",
          age: 11
        }, function(err) {
          return console.log(err);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=repository.test.map
