// Generated by CoffeeScript 1.7.1
(function() {
  var assert;

  assert = require("assert");

  process.env.LIB_COV;

  describe("Array", function() {
    return describe("#indexOf", function() {
      return it("should return -1 when value is not found", function() {
        assert.equal(-1, [1, 2, 3].indexOf(5));
        return assert.equal(-1, [1, 2, 3].indexOf(10));
      });
    });
  });

}).call(this);

//# sourceMappingURL=repository.test.map
