// Generated by CoffeeScript 1.7.1
(function() {
  var path;

  path = require("path");

  module.exports = function(path) {
    var e;
    try {
      return require("../lib-cov/" + path);
    } catch (_error) {
      e = _error;
      return require("../lib/" + path);
    }
  };

}).call(this);

//# sourceMappingURL=require.map
