// Generated by CoffeeScript 1.7.1
(function() {
  var log4js, logger;

  log4js = require("log4js");

  logger = function() {};

  logger.getLogger = function(category) {
    if (category == null) {
      category = "default";
    }
    return log4js.getLogger(category);
  };

  module.exports = logger;

}).call(this);

//# sourceMappingURL=logger.map
