// Generated by LiveScript 1.2.0
(function(){
  var file;
  file = (function(){
    file.displayName = 'file';
    var prototype = file.prototype, constructor = file;
    file.loadConfigFileSync = function(path){
      if (path) {
        return JSON.parse(fs.readFileSync(path, 'utf8'));
      }
      return undefined;
    };
    function file(){}
    return file;
  }());
  module.exports = file;
}).call(this);
