// Generated by LiveScript 1.2.0
(function(){
  var consts, redisClient, flash;
  consts = require('../consts');
  redisClient = require('../helpers/redis');
  flash = (function(){
    flash.displayName = 'flash';
    var prototype = flash.prototype, constructor = flash;
    flash.yieldIsExists = function(key, seconds){
      var redis;
      seconds == null && (seconds = consts.FLASH_TIMEOUT);
      if (!key) {
        throw new Error('key is required.');
      }
      redis = new redisClient();
      return function*(){
        var isExists;
        isExists = yield function(done){
          return redis.exists(key, function(err, flag){
            return done(err, flag);
          });
        };
        if (1 === isExists) {
          return true;
        } else {
          yield function(done){
            return redis.set(key, '', function(err, flag){
              if ('OK' === flag) {
                return redis.expire(key, seconds, function(err, flag){
                  return done(err, flag);
                });
              }
            });
          };
          return false;
        }
      };
    };
    function flash(){}
    return flash;
  }());
  module.exports = flash;
}).call(this);
