// Generated by LiveScript 1.2.0
(function(){
  var mongoose, curriculumSchema;
  mongoose = require('mongoose');
  curriculumSchema = new mongoose.Schema({
    classId: {
      type: mongoose.Schema.ObjectId
    },
    title: {
      type: String
    },
    description: {
      type: String
    },
    start: {
      type: Date
    },
    end: {
      type: Date
    },
    allDay: {
      type: Boolean
    },
    level: {
      type: Number
    }
  });
  module.exports = curriculumSchema;
}).call(this);
