// Generated by CoffeeScript 1.7.1
(function() {
  var consts, mongoose, repository_base, user_repository, user_schema,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  consts = require("../consts/consts");

  mongoose = require("mongoose");

  user_schema = require("../schema/user_schema");

  repository_base = require("./repository_base");

  user_repository = (function(_super) {
    __extends(user_repository, _super);

    function user_repository() {
      user_repository.__super__.constructor.call(this, consts.MONGODB_CONFIG_PATH);
      this.model = this.connection.model("user", user_schema);
    }

    user_repository.prototype.findMaxAge = function(next) {
      return this.model.findOne().sort({
        age: -1
      }).exec(next);
    };

    return user_repository;

  })(repository_base);

  module.exports = user_repository;

}).call(this);

//# sourceMappingURL=user_repository.map
