// Generated by LiveScript 1.2.0
(function(){
  var crypto, encrypt;
  crypto = require('crypto');
  encrypt = (function(){
    encrypt.displayName = 'encrypt';
    var prototype = encrypt.prototype, constructor = encrypt;
    encrypt.sha1Hash = function(str){
      var hasher;
      hasher = crypto.createHash("sha1");
      return hasher.update(str).digest("hex");
    };
    function encrypt(){}
    return encrypt;
  }());
  module.exports = encrypt;
}).call(this);
