// Generated by LiveScript 1.2.0
(function(){
  var views, list;
  views = require('../helper/views');
  this.list = list = (function(){
    list.displayName = 'list';
    var prototype = list.prototype, constructor = list;
    list.get = function*(){
      this.body = yield views.hogan.render('curriculum/list');
    };
    function list(){}
    return list;
  }());
}).call(this);
