// Generated by LiveScript 1.2.0
(function(){
  var curm_rep, views, list;
  curm_rep = require('../repositories/curriculum_repository');
  views = require('../helpers/views');
  this.list = list = (function(){
    list.displayName = 'list';
    var prototype = list.prototype, constructor = list;
    list.get = function*(){
      var curmRep, data;
      curmRep = new curm_rep();
      data = yield function(done){
        return curmRep.findAll({
          classId: '54226f9bd3b74372fc21d9a9'
        }, done);
      };
      this.body = yield views.hogan.render('curriculum/list', {
        data: data
      });
    };
    function list(){}
    return list;
  }());
}).call(this);
