// Generated by LiveScript 1.2.0
(function(){
  var views, index;
  views = require('../helpers/views');
  this.index = index = (function(){
    index.displayName = 'index';
    var prototype = index.prototype, constructor = index;
    index.get = function*(){
      this.body = yield views.hogan.render('home/index');
    };
    function index(){}
    return index;
  }());
}).call(this);
