// Generated by LiveScript 1.2.0
(function(){
  var index;
  this.index = index = (function(){
    index.displayName = 'index';
    var prototype = index.prototype, constructor = index;
    index.get = function*(){
      var query, req;
      query = this.query;
      req = this.req;
      console.log(req);
      this.body = "get in home;query: " + query + " ;  req: " + req;
    };
    function index(){}
    return index;
  }());
  module.exports = this;
}).call(this);
