// Generated by LiveScript 1.2.0
(function(){
  var mongoose, settingSchema;
  mongoose = require('mongoose');
  settingSchema = new mongoose.Schema({
    welcome: {
      type: String
    }
  });
}).call(this);
