// Generated by CoffeeScript 1.7.1
(function() {
  var async, mongoose, user_rep, user_repository, user_schema;

  user_repository = require("../repository/user_repository");

  async = require("async");

  mongoose = require("mongoose");

  user_schema = require("../schema/user_schema");

  user_rep = new user_repository();

  user_rep.findMaxAge(function(err, data) {
    return console.log(data);
  });

}).call(this);

//# sourceMappingURL=mongo_test.map
